import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "EShop",
    description: "Generated by create next app",
};

export default function EShopLayout({children}:{children: React.ReactNode;}) {
    return (
        <>
            {children}
        </>
    );
}
