import Layout from "@/components/layouts/EShopLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "EShop",
    description: "Generated by create next app",
};

export default function EShopLayout({children,}: {children: React.ReactNode;}) {
    return <Layout>{children}</Layout>;
}
